services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --max_allowed_packet=128M
    networks:
      - my_network
    ports:
      - "3306:3306"
    volumes:
      - ./queries/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/Relatorio_cadop.csv:/var/lib/mysql-files/Relatorio_cadop.csv
      - ./data/financial/1T2023.csv:/var/lib/mysql-files/financial/1T2023.csv
      - ./data/financial/1T2024.csv:/var/lib/mysql-files/financial/1T2024.csv
      - ./data/financial/2t2023.csv:/var/lib/mysql-files/financial/2T2023.csv
      - ./data/financial/2T2024.csv:/var/lib/mysql-files/financial/2T2024.csv
      - ./data/financial/3T2023.csv:/var/lib/mysql-files/financial/3T2023.csv
      - ./data/financial/3T2024.csv:/var/lib/mysql-files/financial/3T2024.csv
      - ./data/financial/4T2023.csv:/var/lib/mysql-files/financial/4T2023.csv
      - ./data/financial/4T2024.csv:/var/lib/mysql-files/financial/4T2024.csv

  backend:
    build: ./backend
    environment:
      DATABASE_URL: mysql+pymysql://root@db/intuitive_care
    ports:
      - "8000:8000"
    networks:
      - my_network

  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: http://localhost:8000
    ports:
      - "5173:5173"
    networks:
      - my_network
    command: ["npm", "run", "start", "--", "--host"]

networks:
  my_network:
    driver: bridge