services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --max_allowed_packet=128M
    networks:
      - my_network
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    environment:
      DATABASE_URL: mysql+pymysql://root@db/intuitive_care
    ports:
      - "8000:8000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge