export const mockData = [
  {
    numero: '952',
    telefone: '36234900',
    registro_ans: '418242',
    complemento: '',
    fax: '36234900',
    id: 257,
    bairro: 'SÃO FRANCISCO',
    email: 'diretoria@uniodontorr.com.br',
    cnpj: '01750093000134',
    cidade: 'Boa Vista',
    representante_legal: 'GILENIO PINHEIRO DA SILVA',
    razao_social: 'COOPERATIVA DE SAÚDE ODONTOLÓGICA - UNIODONTO RORAIMA',
    uf: 'RR',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE RORAIMA',
    cep: '69305025',
    regiao_operacao: 6,
    modalidade: 'Cooperativa odontológica',
    ddd: '95',
    data_registro: '2011-09-27',
    logradouro: 'AVENIDA CAPITÃO JULIO BEZERRA',
  },
  {
    numero: '240',
    telefone: '36220258',
    registro_ans: '419028',
    complemento: '',
    fax: '36220258',
    id: 262,
    bairro: 'VARGINHA',
    email: 'uniodonto@uniodontoitajuba.com.br',
    cnpj: '25906728000108',
    cidade: 'Itajubá',
    representante_legal: 'ALEXANDRE JULIO DIELLE',
    razao_social: 'COOPERATIVA DE TRABALHO ODONTOLOGICO - UNIODONTO ITAJUBÁ',
    uf: 'MG',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: '',
    cep: '37501058',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '35',
    data_registro: '2013-09-11',
    logradouro: 'RUA ALCIDES FARIA',
  },
  {
    numero: '245',
    telefone: '336134760',
    registro_ans: '402010',
    complemento: '1º ANDAR',
    fax: '36134760',
    id: 270,
    bairro: 'CENTRO',
    email: 'uniodontoitb@gmail.com',
    cnpj: '00491998000174',
    cidade: 'Itabuna',
    representante_legal: 'MARIO AUGUSTO DIAS BRUM',
    razao_social: 'COOPERATIVA ODONTOLÓGICA REGIÃO SUL DA BAHIA - UNIODONTO',
    uf: 'BA',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO ITABUNA',
    cep: '45600120',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '07',
    data_registro: '1999-03-12',
    logradouro: 'RUA MARIÁ FERREIRA',
  },
  {
    numero: '88',
    telefone: '',
    registro_ans: '414891',
    complemento: '',
    fax: '',
    id: 980,
    bairro: 'MAURÍCIO DE NASSAU',
    email: 'uniodontocaruaru@hotmail.com',
    cnpj: '01141489000184',
    cidade: 'Caruaru',
    representante_legal: 'RÔNIO DE MEDEIROS GALINDO',
    razao_social:
      'UNIODONTO - COOPERATIVA ODONTOLOGICA DE CARUARU E REGIÃO AGRESTE DO ESTADO DE PERNAMBUCO',
    uf: 'PE',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO CARUARU',
    cep: '55012530',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '',
    data_registro: '2004-05-21',
    logradouro: 'RUA RÁDIO CLUBE DE PERNAMBUCO',
  },
  {
    numero: '43',
    telefone: '35222383',
    registro_ans: '403512',
    complemento: '',
    fax: '35223429',
    id: 981,
    bairro: 'ALTO DO CRUZEIRO',
    email: 'uniodonto@uniodontoarapiraca.com.br',
    cnpj: '02988689000130',
    cidade: 'Arapiraca',
    representante_legal: 'CLAUDIA VALERIA LIRA BARBOSA ',
    razao_social:
      'UNIODONTO ARAPIRACA COOPERATIVA DE TRABALHO ODONTOLÓGICO LTDA',
    uf: 'AL',
    cargo_representante: 'REPRESENTANTE LEGAL',
    nome_fantasia: 'UNIODONTO ARAPIRACA',
    cep: '57312480',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '82',
    data_registro: '1999-04-14',
    logradouro: 'RUA PADRE JEFERSON DE CARVALHO',
  },
  {
    numero: '340',
    telefone: '32021601',
    registro_ans: '340120',
    complemento: '',
    fax: '32021601',
    id: 982,
    bairro: 'NOVA JABOTICABAL',
    email: 'joaoleonardo@uniodontoathenas.coop.br',
    cnpj: '00390564000188',
    cidade: 'Jaboticabal',
    representante_legal: 'JOÃO LEONARDO DELLA LIBERA FILHO',
    razao_social: 'UNIODONTO ATHENAS PAULISTA - COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'VICE-PRESIDENTE DE ADMINISTRAÇÃO E FINAN',
    nome_fantasia: 'UNIODONTO DE JABOTICABAL',
    cep: '14887030',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '16',
    data_registro: '1998-12-16',
    logradouro: 'RUA SANTO ANDRÉ',
  },
  {
    numero: '386',
    telefone: '36347050',
    registro_ans: '383929',
    complemento: '',
    fax: '36347050',
    id: 983,
    bairro: 'CENTRO',
    email: 'gerenciaadm@uniodontobahiasul.com.br',
    cnpj: '00629608000180',
    cidade: 'Ilhéus',
    representante_legal: 'LUCIANO MOREIRA TAVARES',
    razao_social:
      'UNIODONTO BAHIA SUL - COOPERATIVA ODONTOLOGICA DE ILHEUS RESPONSABILIDADE LTDA',
    uf: 'BA',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO BAHIA SUL',
    cep: '45653005',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '73',
    data_registro: '1999-02-02',
    logradouro: 'AVENIDA SOARES LOPES',
  },
  {
    numero: '1261',
    telefone: '33440700',
    registro_ans: '327093',
    complemento: '',
    fax: '33440700',
    id: 984,
    bairro: 'CENTRO',
    email: 'adm@uniodontobebedouro.coop.br',
    cnpj: '66095423000140',
    cidade: 'Bebedouro',
    representante_legal: 'JOÃO PAULO TOLLER',
    razao_social: 'UNIODONTO BEBEDOURO - COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO ',
    cep: '14700340',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '17',
    data_registro: '1998-12-17',
    logradouro: 'RUA VICENTE PASCHOAL',
  },
  {
    numero: '1212',
    telefone: '32024140',
    registro_ans: '368555',
    complemento: '',
    fax: '',
    id: 985,
    bairro: 'NAZARÉ',
    email: 'uniodopa@uniodontobelem.com.br',
    cnpj: '15308521000188',
    cidade: 'Belém',
    representante_legal: 'ARIOSTO MARIA CHAVES DIAS',
    razao_social:
      'UNIODONTO BELÉM - COOPERATIVA DE ASSISTÊNCIA À SAÚDE ODONTOLÓGICA',
    uf: 'PA',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO',
    cep: '66040000',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '91',
    data_registro: '1998-12-29',
    logradouro: 'AV GENTIL BITTENCOURT',
  },
  {
    numero: '745',
    telefone: '137143444',
    registro_ans: '353752',
    complemento: 'SALA 204',
    fax: '',
    id: 986,
    bairro: 'CENTRO',
    email: 'admsc@uniodontovtrp.com.br',
    cnpj: '87303772000180',
    cidade: 'Lajeado',
    representante_legal: 'DITMAR ARY KUHN',
    razao_social: 'UNIODONTO COOP ODONT VALE TAQUARI E RIO PARDO LTDA',
    uf: 'RS',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO COOP ODONT VALE TAQUARI E RIO PARDO LTDA',
    cep: '95900000',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '05',
    data_registro: '1998-12-18',
    logradouro: 'AV. JÚLIO DE CASTILHOS',
  },
  {
    numero: '663',
    telefone: '34211477',
    registro_ans: '343919',
    complemento: '',
    fax: '844173799',
    id: 987,
    bairro: 'CENTRO',
    email: 'uniodontoserido@terra.com.br',
    cnpj: '01751280000132',
    cidade: 'Caicó',
    representante_legal: 'MARCO POLO AYRES DO RÊGO',
    razao_social: 'UNIODONTO COOPERATIVA ODONTOLÓGICA DO SERIDÓ LTDA',
    uf: 'RN',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DO SERIDÓ',
    cep: '59300000',
    regiao_operacao: 6,
    modalidade: 'Cooperativa odontológica',
    ddd: '84',
    data_registro: '1998-12-30',
    logradouro: 'RUA SENADOR JOSÉ BERNARDO ',
  },
  {
    numero: '105',
    telefone: '34616728',
    registro_ans: '347604',
    complemento: 'VILA PAVAN',
    fax: '34611430',
    id: 988,
    bairro: 'CENTRO',
    email: 'uniodontoamer@uol.com.br',
    cnpj: '69015113000167',
    cidade: 'Americana',
    representante_legal: 'SILNEY MARCOS BERALDO',
    razao_social: 'UNIODONTO DE AMERICANA COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE AMERICANA COOPERATIVA ODONTOLÓGICA',
    cep: '13465000',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '19',
    data_registro: '1998-12-17',
    logradouro: 'RUA PADRE ANCHIETA',
  },
  {
    numero: '265',
    telefone: '40095454',
    registro_ans: '349283',
    complemento: '',
    fax: '40095450',
    id: 989,
    bairro: 'SALGADO FILHO',
    email: 'uniodont@infonet.com.br',
    cnpj: '32844169000114',
    cidade: 'Aracaju',
    representante_legal: 'LIOMAR MARIA DE OLIVEIRA QUARANTA',
    razao_social: 'UNIODONTO DE ARACAJU COOP DE TRABALHO ODONTOLOGICO',
    uf: 'SE',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE ARACAJU COOPERATIVA DE TRABALHO ODONTOLOGICO',
    cep: '49020330',
    regiao_operacao: 6,
    modalidade: 'Cooperativa odontológica',
    ddd: '79',
    data_registro: '1998-12-18',
    logradouro: 'RUA JOVENTINA ALVES',
  },
  {
    numero: '1947',
    telefone: '33321700',
    registro_ans: '316997',
    complemento: '',
    fax: '33037131',
    id: 990,
    bairro: 'CENTRO',
    email: 'araraquara@uniodontoararaquara.com.br',
    cnpj: '65442162000125',
    cidade: 'Araraquara',
    representante_legal: 'GUSTAVO LORIA LEONI',
    razao_social: 'UNIODONTO DE ARARAQUARA COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE ARARAQUARA',
    cep: '14801320',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '16',
    data_registro: '1998-12-16',
    logradouro: 'RUA VOLUNTARIOS DA PATRIA',
  },
  {
    numero: '310',
    telefone: '31175271',
    registro_ans: '362824',
    complemento: '',
    fax: '31175273',
    id: 991,
    bairro: 'CENTRO',
    email: 'uniodontoaracatuba@terra.com.br',
    cnpj: '01856688000179',
    cidade: 'Araçatuba',
    representante_legal: 'PAULO CEZAR BATAGELO',
    razao_social: 'UNIODONTO DE ARAÇATUBA COOPERATIVA ODONTOLOGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO ARACATUBA',
    cep: '16010290',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '18',
    data_registro: '1998-12-21',
    logradouro: 'RUA GENERAL OSÓRIO',
  },
  {
    numero: '1001',
    telefone: '37322303',
    registro_ans: '311669',
    complemento: '',
    fax: '',
    id: 992,
    bairro: 'CENTRO',
    email: 'uniodontoavare@uol.com.br',
    cnpj: '00014922000158',
    cidade: 'Avaré',
    representante_legal: 'WALDIR CÉSAR DE SOUZA',
    razao_social: 'UNIODONTO DE AVARE COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE AVARE',
    cep: '18700160',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '14',
    data_registro: '1998-12-16',
    logradouro: 'RUA DISTRITO FEDERAL',
  },
  {
    numero: '1310',
    telefone: '',
    registro_ans: '347477',
    complemento: '',
    fax: '',
    id: 993,
    bairro: 'CENTRO',
    email: 'uniodontobotu@uol.com.br',
    cnpj: '01946395000182',
    cidade: 'Botucatu',
    representante_legal: 'SERGIO HENRIQUE BAUER',
    razao_social: 'UNIODONTO DE BOTUCATU COOPERATIVA ODONTOLOGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO BOTUCATU',
    cep: '18600040',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '',
    data_registro: '1998-12-16',
    logradouro: 'RUA JOAO PASSOS',
  },
  {
    numero: '20',
    telefone: '36525619',
    registro_ans: '347302',
    complemento: '',
    fax: '36525373',
    id: 994,
    bairro: 'CENTRO',
    email: 'uniodontocacapava@gmail.com',
    cnpj: '00022130000125',
    cidade: 'Caçapava',
    representante_legal: 'MARIA ANGELICA GIOVANELLI',
    razao_social: 'UNIODONTO DE CACAPAVA COOPERATIVA ODONTOLOGICA',
    uf: 'SP',
    cargo_representante: 'SUPERINTENDENTE',
    nome_fantasia: 'UNIODONTO',
    cep: '12281350',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '12',
    data_registro: '1998-12-16',
    logradouro: 'RUA CEL JOÃO  DIAS GUIMARÃES',
  },
  {
    numero: '200',
    telefone: '33224000',
    registro_ans: '350494',
    complemento: '',
    fax: '33224006',
    id: 995,
    bairro: 'VILA ITAPURA',
    email: 'jsilva@uniodontocampinas.com.br',
    cnpj: '51304798000104',
    cidade: 'Campinas',
    representante_legal: 'VLADIMIR BORIN PACHECO JUNIOR',
    razao_social: 'UNIODONTO DE CAMPINAS COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE CAMPINAS',
    cep: '13023075',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '19',
    data_registro: '1998-12-16',
    logradouro: 'AV BRASIL',
  },
  {
    numero: '1463',
    telefone: '30298040',
    registro_ans: '347183',
    complemento: '',
    fax: '30298040',
    id: 996,
    bairro: 'CENTRO',
    email: 'unicgde@terra.com.br',
    cnpj: '03511888000115',
    cidade: 'Campo Grande',
    representante_legal: 'FERNANDO JAIME CAVALLI',
    razao_social: 'UNIODONTO DE CAMPO GRANDE SIST. NAC. COOP. ODONT.',
    uf: 'MS',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO MATO GROSSO DO SUL',
    cep: '79002221',
    regiao_operacao: 3,
    modalidade: 'Cooperativa odontológica',
    ddd: '67',
    data_registro: '1998-12-21',
    logradouro: 'RUA ANTONIO MARIA COELHO',
  },
  {
    numero: '416',
    telefone: '33435086',
    registro_ans: '402516',
    complemento: 'LOJA 218',
    fax: '27334321',
    id: 997,
    bairro: 'CENTRO',
    email: 'gerencia@uniodontocampos.com.br',
    cnpj: '03005846000102',
    cidade: 'Campos dos Goytacazes',
    representante_legal: 'MARCOS LINCOLN DE SOUZA MUNIZ JUNIOR',
    razao_social: 'UNIODONTO DE CAMPOS - COOPERATIVA ODONTOLOGICA',
    uf: 'RJ',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE CAMPOS COOPERATIVA ODONTOLOGICA',
    cep: '28010270',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '17',
    data_registro: '1999-03-24',
    logradouro: 'RUA SALDANHA MARINHO',
  },
  {
    numero: '141',
    telefone: '35232516',
    registro_ans: '354686',
    complemento: '',
    fax: '35232516',
    id: 998,
    bairro: 'CENTRO',
    email: 'uniodonto@uniodontocatanduva.com.br',
    cnpj: '00855599000145',
    cidade: 'Catanduva',
    representante_legal: 'JOSÉ EDUARDO HADDAD',
    razao_social: 'UNIODONTO DE CATANDUVA COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE CATANDUVA',
    cep: '15800225',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '17',
    data_registro: '1998-12-16',
    logradouro: 'PRAÇA 9 DE JULHO',
  },
  {
    numero: '1511',
    telefone: '',
    registro_ans: '400556',
    complemento: '2º andar , sala 208 - Edifício Meritum C',
    fax: '',
    id: 999,
    bairro: 'CENTRO',
    email: 'uniodontofs@ig.com.br',
    cnpj: '16325896000119',
    cidade: 'Feira de Santana',
    representante_legal: 'CAMILA DOREA FERNANDES SILVA',
    razao_social:
      'UNIODONTO DE FEIRA DE SANTANA - COOPERATIVA DE TRABALHO ODONTOLÓGICO DE FEIRA DE SANTANA RESP LIMITADA',
    uf: 'BA',
    cargo_representante: 'DIRETORA PRESIDENTE',
    nome_fantasia: 'UNIODONTO FEIRA DE SANTANA',
    cep: '44001184',
    regiao_operacao: 6,
    modalidade: 'Cooperativa odontológica',
    ddd: '',
    data_registro: '1999-02-13',
    logradouro: 'RUA CASTRO ALVES',
  },
  {
    numero: '830',
    telefone: '91663484',
    registro_ans: '301647',
    complemento: 'TERREO',
    fax: '34626000',
    id: 1000,
    bairro: 'CENTRO',
    email: 'uniodontofer@terra.com.br',
    cnpj: '02015569000156',
    cidade: 'Fernandópolis',
    representante_legal: 'EDUARDO HAMILTON D¿AVILA',
    razao_social: 'UNIODONTO DE FERNANDOPOLIS COOPERATIVA ODONTOLOGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: '',
    cep: '15600000',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '17',
    data_registro: '1998-12-16',
    logradouro: 'AV DOS ARNALDOS',
  },
  {
    numero: '915',
    telefone: '40095442',
    registro_ans: '335258',
    complemento: '',
    fax: '40095442',
    id: 1001,
    bairro: 'CENTRO',
    email: 'contabil@uniodonto-ce.com.br',
    cnpj: '23725062000166',
    cidade: 'Fortaleza',
    representante_legal: 'MARLIO XIMENES CARLOS',
    razao_social:
      'UNIODONTO DE FORTALEZA COOPERATIVA DE TRABALHO ODONTOLOGICO LTDA',
    uf: 'CE',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE FORTALEZA',
    cep: '60160280',
    regiao_operacao: 3,
    modalidade: 'Cooperativa odontológica',
    ddd: '85',
    data_registro: '1998-12-29',
    logradouro: 'RUA  COSTA BARROS',
  },
  {
    numero: '2444',
    telefone: '36322293',
    registro_ans: '309257',
    complemento: '',
    fax: '36322293',
    id: 1002,
    bairro: 'CENTRO',
    email: 'uniodontojales@terra.com.br',
    cnpj: '02085247000183',
    cidade: 'Jales',
    representante_legal: 'FLAVIA MARTIM',
    razao_social: 'UNIODONTO DE JALES - COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'VOGAL',
    nome_fantasia: '',
    cep: '15700000',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '17',
    data_registro: '1998-12-17',
    logradouro: 'RUA SETE',
  },
  {
    numero: '541',
    telefone: '21075858',
    registro_ans: '361569',
    complemento: '',
    fax: '',
    id: 1003,
    bairro: 'CENTRO',
    email: 'uniodontojp@uniodontojp.com.br',
    cnpj: '12923462000160',
    cidade: 'João Pessoa',
    representante_legal: 'TERTULIANO BRITO NETO',
    razao_social: 'UNIODONTO DE JOÃO PESSOA COOPERATIVA ODONTOLÓGICA',
    uf: 'PB',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO JOAO PESSOA',
    cep: '58013280',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '83',
    data_registro: '1998-12-17',
    logradouro: 'AV. DUARTE DA SILVEIRA',
  },
  {
    numero: '211',
    telefone: '148059999',
    registro_ans: '347795',
    complemento: '',
    fax: '148059999',
    id: 1004,
    bairro: 'CENTRO',
    email: 'gerencia@uniodontojundiai.com.br',
    cnpj: '59527440000144',
    cidade: 'Jundiaí',
    representante_legal: 'JOSE CLOVIS TOMAZZONI DE OLIVEIRA',
    razao_social: 'UNIODONTO DE JUNDIAÍ COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE JUNDIAÍ',
    cep: '13201080',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '01',
    data_registro: '1998-12-16',
    logradouro: 'RUA PETRONILHA ANTUNES',
  },
  {
    numero: '70',
    telefone: '34427899',
    registro_ans: '369462',
    complemento: '',
    fax: '34427899',
    id: 1005,
    bairro: 'JARDIM MERCEDES',
    email: 'gerencia@uniodontolimeira.com.br',
    cnpj: '63062350000100',
    cidade: 'Limeira',
    representante_legal: 'JOSEMARY APARECIDA PAERÓ DE BARROS CAMARGO',
    razao_social: 'UNIODONTO DE LIMEIRA COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'DIRETORA DE OPERAÇÕES',
    nome_fantasia: 'UNIODONTO DE LIMEIRA',
    cep: '13480171',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '19',
    data_registro: '1998-12-17',
    logradouro: 'RUA TREZE DE MAIO',
  },
  {
    numero: '880',
    telefone: '35235252',
    registro_ans: '344681',
    complemento: '',
    fax: '',
    id: 1006,
    bairro: 'CENTRO',
    email: 'gerencia@uniodontolins.com.br',
    cnpj: '00847821000168',
    cidade: 'Lins',
    representante_legal: 'ADRIANA MOYA MARTELLI',
    razao_social: 'UNIODONTO DE LINS COOPERATIVA ODONTOLOGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE LINS COOPERATIVA ODONTOLÓGICA',
    cep: '16400106',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '14',
    data_registro: '1998-12-16',
    logradouro: 'RUA PEDRO DE TOLEDO',
  },
  {
    numero: '956',
    telefone: '33057000',
    registro_ans: '350770',
    complemento: '',
    fax: '33057000',
    id: 1007,
    bairro: 'JARDIM AMERICA',
    email: 'claudio@uniodontolondrina.coop.br',
    cnpj: '82239476000144',
    cidade: 'Londrina',
    representante_legal: 'MARCELO FANECO FONTANA',
    razao_social: 'UNIODONTO DE LONDRINA COOP. ODONTOLÓGICA',
    uf: 'PR',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE LONDRINA COOP. ODONTOLÓGICA',
    cep: '86010610',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '43',
    data_registro: '1999-01-06',
    logradouro: 'RUA PAES LEME',
  },
  {
    numero: '598',
    telefone: '21260600',
    registro_ans: '311391',
    complemento: '',
    fax: '',
    id: 1008,
    bairro: 'CENTRO',
    email: 'atendimento@uniodontomao.com.br',
    cnpj: '23031479000129',
    cidade: 'Manaus',
    representante_legal: 'MICHELE PASCHOALOTTI LEMOS',
    razao_social: 'UNIODONTO DE MANAUS - COOPERATIVA ODONTOLÓGICA LTDA.',
    uf: 'AM',
    cargo_representante: 'DIRETORA EXECUTIVA',
    nome_fantasia: 'UNIODONTO MANAUS',
    cep: '69010170',
    regiao_operacao: 6,
    modalidade: 'Cooperativa odontológica',
    ddd: '92',
    data_registro: '1998-12-22',
    logradouro: 'RUA LEONARDO MALCHER',
  },
  {
    numero: '448',
    telefone: '36176500',
    registro_ans: '343404',
    complemento: '',
    fax: '36176523',
    id: 1009,
    bairro: 'DOM AQUINO',
    email: 'adm@uniodontomt.com.br',
    cnpj: '37496767000163',
    cidade: 'Cuiabá',
    representante_legal: 'ERNESTO FARIA DE FIGUEIREDO JUNIOR',
    razao_social: 'UNIODONTO DE MATO GROSSO COOP TRAB ODONTOLOGICO LTDA',
    uf: 'MT',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO MATO GROSSO',
    cep: '78015300',
    regiao_operacao: 3,
    modalidade: 'Cooperativa odontológica',
    ddd: '65',
    data_registro: '1998-12-28',
    logradouro: 'AV. GENERAL MELLO',
  },
  {
    numero: '597',
    telefone: '32425776',
    registro_ans: '336238',
    complemento: '',
    fax: '32432772',
    id: 1010,
    bairro: 'CENTRO',
    email: 'uniodontoma@uol.com.br',
    cnpj: '01592738000158',
    cidade: 'Monte Alto',
    representante_legal: 'ADRIEN CÉSAR GATO',
    razao_social: 'UNIODONTO DE MONTE ALTO COOPERATIVA ODONTOLOGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE MONTE ALTO',
    cep: '15910000',
    regiao_operacao: 6,
    modalidade: 'Cooperativa odontológica',
    ddd: '16',
    data_registro: '1998-12-16',
    logradouro: 'RUA GUSTAVO DE GODOY',
  },
  {
    numero: '51',
    telefone: '36446000',
    registro_ans: '331104',
    complemento: '',
    fax: '',
    id: 1011,
    bairro: 'CENTRO',
    email: 'uniodontopinda@uniodontopinda.com.br',
    cnpj: '02064028000118',
    cidade: 'Pindamonhangaba',
    representante_legal: 'ACÍLIA APARECIDA CÉSAR LOURENÇO',
    razao_social: 'UNIODONTO DE PINDAMONHANGABA COOP ODONTOLOGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO PINDAMONHANGABA',
    cep: '12400190',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '12',
    data_registro: '1998-12-17',
    logradouro: 'PRAÇA PADRE JOÃO FARIA FIALHO',
  },
  {
    numero: '454',
    telefone: '39017764',
    registro_ans: '336017',
    complemento: '',
    fax: '39017765',
    id: 1012,
    bairro: 'VILA MACHADINHO',
    email: 'uniodonto@uniodontoprudente.com.br',
    cnpj: '00172586000171',
    cidade: 'Presidente Prudente',
    representante_legal: 'EDUARDO MITSUO OTIAI',
    razao_social: 'UNIODONTO DE PRESIDENTE PRUDENTE COOPERATIVA ODONTOLOGICA',
    uf: 'SP',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE PRESIDENTE PRUDENTE COOPERATIVA ODONTOLÓGICA',
    cep: '19020120',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '18',
    data_registro: '1998-12-17',
    logradouro: 'AVENIDA CORONEL JOSÉ SOARES MARCONDES',
  },
  {
    numero: '172',
    telefone: '33661888',
    registro_ans: '305740',
    complemento: 'SALA 902 - EMPRESARIAL DESEMBARGADOR  PE',
    fax: '33661875',
    id: 1013,
    bairro: 'BOA VISTA',
    email: 'anayramaltez@uniodontorecife.com.br',
    cnpj: '24125122000172',
    cidade: 'Recife',
    representante_legal: 'ANAYRA SILVANA DA CUNHA MALTEZ',
    razao_social: 'UNIODONTO DE RECIFE - COOPERATIVA ODONTOLÓGICA',
    uf: 'PE',
    cargo_representante: 'DIRETORA PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE RECIFE - COOPERATIVA ODONTOLÓGICA',
    cep: '50050250',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '81',
    data_registro: '1998-12-18',
    logradouro: 'RUA MONTEVIDÉU',
  },
  {
    numero: '2219',
    telefone: '21026500',
    registro_ans: '403997',
    complemento: '',
    fax: '',
    id: 1014,
    bairro: 'DOM GIOCONDO',
    email: 'uniodonto@uniodontoacre.com.br',
    cnpj: '02948490000188',
    cidade: 'Rio Branco',
    representante_legal: 'EDIANA DE FÁTIMA MELO MAGELA',
    razao_social: 'UNIODONTO DE RIO BRANCO ACRE COOPERATIVA ODONTOLÓGICA LTDA.',
    uf: 'AC',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO - AC',
    cep: '69900303',
    regiao_operacao: 6,
    modalidade: 'Cooperativa odontológica',
    ddd: '68',
    data_registro: '1999-04-28',
    logradouro: 'AV. CEARÁ',
  },
  {
    numero: '918',
    telefone: '35246475',
    registro_ans: '349011',
    complemento: 'AVS.3 E 5',
    fax: '35248738',
    id: 1015,
    bairro: 'CENTRO',
    email: 'uniodontorc@uniodontorc.com.br',
    cnpj: '96609292000133',
    cidade: 'Rio Claro',
    representante_legal: 'ROSANGELA DA SILVEIRA FREITAS',
    razao_social: 'UNIODONTO DE RIO CLARO COOPERATIVA ODONTOLOGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE RIO CLARO',
    cep: '13500150',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '19',
    data_registro: '1998-12-17',
    logradouro: 'RUA 2',
  },
  {
    numero: '1783',
    telefone: '32233320',
    registro_ans: '336025',
    complemento: '',
    fax: '32233315',
    id: 1016,
    bairro: 'PEDRINHAS',
    email: 'gerencia@uniodontorondonia.com.br',
    cnpj: '02742094000108',
    cidade: 'Porto Velho',
    representante_legal: 'DIMAS RIBEIRO DA FONSECA JUNIOR',
    razao_social: 'UNIODONTO DE RONDONIA COOPERATIVA LTDA.',
    uf: 'RO',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE RONDÔNIA',
    cep: '76801492',
    regiao_operacao: 6,
    modalidade: 'Cooperativa odontológica',
    ddd: '69',
    data_registro: '1998-12-29',
    logradouro: 'RUA JAMARY ',
  },
  {
    numero: '01',
    telefone: '40099696',
    registro_ans: '310107',
    complemento: 'SALA 205/206',
    fax: '',
    id: 1017,
    bairro: 'COMERCIO',
    email: 'adm@uniodontosalvador.com.br',
    cnpj: '13416391000171',
    cidade: 'Salvador',
    representante_legal: 'OTAILDO CONCEIÇÃO DE OLIVEIRA',
    razao_social:
      'UNIODONTO DE SALVADOR - COOPERATIVA DE TRABALHO ODONTOLÓGICO LTDA.',
    uf: 'BA',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO SALVADOR',
    cep: '40015090',
    regiao_operacao: 6,
    modalidade: 'Cooperativa odontológica',
    ddd: '71',
    data_registro: '1999-01-04',
    logradouro: 'RUA FRANCISCO GONÇALVES',
  },
  {
    numero: '05',
    telefone: '36816729',
    registro_ans: '378682',
    complemento: '',
    fax: '36814229',
    id: 1018,
    bairro: 'CENTRO',
    email: 'financeiro@uniodontosjrpardo.com.br',
    cnpj: '01221295000199',
    cidade: 'São José do Rio Pardo',
    representante_legal: 'ADRIANO CALSONE',
    razao_social:
      'UNIODONTO DE SAO JOSE DO RIO PARDO - COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO SÃO JOSÉ DO RIO PARDO',
    cep: '13720000',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '19',
    data_registro: '1998-12-16',
    logradouro: 'AVENIDA INDEPENDÊNCIA',
  },
  {
    numero: '123',
    telefone: '30378000',
    registro_ans: '342203',
    complemento: 'CASA',
    fax: '30378000',
    id: 1019,
    bairro: 'CENTRO',
    email: 'cpd@uniodontosc.com.br',
    cnpj: '02338268000163',
    cidade: 'Blumenau',
    representante_legal: 'RUBENS RENATO WEIDGENANT',
    razao_social: 'UNIODONTO DE SC COOPERATIVA ADMINISTRADORA DE CONTRATOS',
    uf: 'SC',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO ADMINISTRADORA',
    cep: '89010250',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '47',
    data_registro: '1998-12-18',
    logradouro: 'RUA VITÓRIA',
  },
  {
    numero: '684',
    telefone: '621056700',
    registro_ans: '373109',
    complemento: '',
    fax: '',
    id: 1020,
    bairro: 'CENTRO',
    email: 'uniodonto@uniodontosertaozinho.com.br',
    cnpj: '00826676000139',
    cidade: 'Sertãozinho',
    representante_legal: 'APARECIDO SILVIO DE SOUZA ',
    razao_social: 'UNIODONTO DE SERTAOZINHO SP COOPERATIVA ODONTOLOGICA',
    uf: 'SP',
    cargo_representante: 'REPRESENTANTE',
    nome_fantasia: 'UNIODONTO DE SERTAOZINHO',
    cep: '14160020',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '01',
    data_registro: '1998-12-16',
    logradouro: 'RUA CARLOS GOMES',
  },
  {
    numero: '628',
    telefone: '32349424',
    registro_ans: '334243',
    complemento: '',
    fax: '32349424',
    id: 1021,
    bairro: 'J. VERGUEIRO',
    email: 'uniodontosor@uniodontosorocaba.com.br',
    cnpj: '58702853000155',
    cidade: 'Sorocaba',
    representante_legal: 'VALERIA REGINA ATHAYDE',
    razao_social: 'UNIODONTO DE SOROCABA COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO SOROCABA',
    cep: '18030000',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '15',
    data_registro: '1998-12-16',
    logradouro: 'AV. BARÃO DE TATUI',
  },
  {
    numero: '24',
    telefone: '32026000',
    registro_ans: '313751',
    complemento: '',
    fax: '39422946',
    id: 1022,
    bairro: 'CENTRO',
    email: 'uniodontosjc@uniodontosjc.com.br',
    cnpj: '73162760000179',
    cidade: 'São José dos Campos',
    representante_legal: 'SERGIO BRITO',
    razao_social:
      'UNIODONTO DE SÃO JOSÉ DOS CAMPOS COOPERATIVA DE TRABALHO ODONTOLÓGICO',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO SÃO JOSÉ DOS CAMPOS',
    cep: '12245730',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '12',
    data_registro: '1998-12-16',
    logradouro: 'PRAÇA PRESIDENTE KENNEDY',
  },
  {
    numero: '1309',
    telefone: '97334972',
    registro_ans: '350290',
    complemento: '',
    fax: '',
    id: 1023,
    bairro: 'CENTRO',
    email: 'rosana@uniodontotaquaritinga.com.br',
    cnpj: '01902941000183',
    cidade: 'Taquaritinga',
    representante_legal: 'ODILON GUEDES BARRETO JUNIOR',
    razao_social: 'UNIODONTO DE TAQUARITINGA COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE TAQUARITINGA COOPERATIVA ODONTOLÓGICA',
    cep: '15900000',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '16',
    data_registro: '1998-12-16',
    logradouro: 'RUA GENERAL OSÓRIO',
  },
  {
    numero: '44',
    telefone: '22553338',
    registro_ans: '359726',
    complemento: 'SALA 315 E 316',
    fax: '22553338',
    id: 1024,
    bairro: 'CENTRO',
    email: 'uniodontotresrios@yahoo.com.br',
    cnpj: '02418863000109',
    cidade: 'Três Rios',
    representante_legal: 'MARISOL GUIMARÃES MACHADO PEREIRA',
    razao_social:
      'UNIODONTO DE TRÊS RIOS - COOPERATIVA DE TRABALHO ODONTOLÓGICA',
    uf: 'RJ',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO TRÊS RIOS',
    cep: '25804130',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '24',
    data_registro: '1998-12-29',
    logradouro: 'TRAVESSA AUGUSTO DE ALMEIDA',
  },
  {
    numero: '2856',
    telefone: '34213395',
    registro_ans: '350630',
    complemento: '',
    fax: '34213395',
    id: 1025,
    bairro: 'SANTA ELISA',
    email: 'uniodonto@votuporanga.com.br',
    cnpj: '01422924000149',
    cidade: 'Votuporanga',
    representante_legal: 'JOSE LUIZ PEREIRA',
    razao_social: 'UNIODONTO DE VOTUPORANGA COOPERATIVA ODONTOLOGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE VOTUPORANGA COOPERATIVA ODONTOLOGICA',
    cep: '15505187',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '17',
    data_registro: '1998-12-16',
    logradouro: 'RUA FREI DAMIÃO',
  },
  {
    numero: '185',
    telefone: '59044400',
    registro_ans: '314315',
    complemento: '',
    fax: '',
    id: 1026,
    bairro: 'PARAÍSO',
    email: 'regulacao@uniodonto.coop.br',
    cnpj: '44595858000111',
    cidade: 'São Paulo',
    representante_legal: 'JOSÉ ALVES DE SOUZA NETO',
    razao_social:
      'UNIODONTO DO BRASIL CENTRAL NACIONAL DAS COOPERATIVAS ODONTÓLOGICAS',
    uf: 'SP',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO DO BRASIL',
    cep: '04104000',
    regiao_operacao: 4,
    modalidade: 'Cooperativa odontológica',
    ddd: '11',
    data_registro: '1998-12-17',
    logradouro: 'RUA CORREIA DIAS ',
  },
  {
    numero: '519',
    telefone: '34317146',
    registro_ans: '358339',
    complemento: '',
    fax: '',
    id: 1027,
    bairro: 'CENTRO',
    email: 'uniodontosulgo@yahoo.com.br',
    cnpj: '37256591000172',
    cidade: 'Itumbiara',
    representante_legal: 'JOAO BATISTA PEREIRA MACHADO',
    razao_social: 'UNIODONTO DO SUL GOIANO COOPERATIVA ODONTOLOGICA',
    uf: 'GO',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO DO SUL GOIANO',
    cep: '75503090',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '64',
    data_registro: '1998-12-17',
    logradouro: 'RUA RUI DE ALMEIDA',
  },
  {
    numero: '2658',
    telefone: '34223577',
    registro_ans: '313807',
    complemento: '',
    fax: '',
    id: 1028,
    bairro: 'JARDIM CENTRAL',
    email: 'uniodonto@dourados.com.br',
    cnpj: '00199703000190',
    cidade: 'Dourados',
    representante_legal: 'EDSON HIROSHI MURAKI',
    razao_social: 'UNIODONTO DOURADOS - COOPERATIVA ODONTOLÓGICA',
    uf: 'MS',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: '',
    cep: '79805031',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '67',
    data_registro: '1999-01-12',
    logradouro: 'RUA CIRO MELLO',
  },
  {
    numero: '50',
    telefone: '35111500',
    registro_ans: '370711',
    complemento: 'EDIF IBISA',
    fax: '35111500',
    id: 1029,
    bairro: 'GILBERTO MACHADO',
    email: 'gerencia@uniodontoes.coop.br',
    cnpj: '02580965000126',
    cidade: 'Cachoeiro de Itapemirim',
    representante_legal: 'ADRIANO BASTOS BARBOSA',
    razao_social: 'UNIODONTO ESPIRITO SANTO COOPERATIVA ODONTOLOGICA',
    uf: 'ES',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO',
    cep: '29303310',
    regiao_operacao: 3,
    modalidade: 'Cooperativa odontológica',
    ddd: '28',
    data_registro: '1998-12-17',
    logradouro: 'RUA RESK SALIN CARONE',
  },
  {
    numero: '1091',
    telefone: '32423833',
    registro_ans: '341894',
    complemento: '',
    fax: '',
    id: 1030,
    bairro: 'CENTRO',
    email: 'adm@uniodontofronteiraoeste.com.br',
    cnpj: '00119565000192',
    cidade: "Sant'Ana do Livramento",
    representante_legal: 'LUIZ FERNANDO MENDONÇA BIDART',
    razao_social: 'UNIODONTO FRONTEIRA OESTE/RS COOPERATIVA ODONTOLÓGICA LTDA.',
    uf: 'RS',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO FRONTEIRA OESTE/RS',
    cep: '97573450',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '55',
    data_registro: '1998-12-17',
    logradouro: 'AV. 24 DE MAIO',
  },
  {
    numero: '1115',
    telefone: '32549100',
    registro_ans: '358436',
    complemento: 'Quadra 65, Lote 4',
    fax: '32549101',
    id: 1031,
    bairro: 'SETOR BUENO',
    email: 'uniodonto@uniodontogoiania.com.br',
    cnpj: '00891689000191',
    cidade: 'Goiânia',
    representante_legal: 'FÁBIO ARAÚJO GONÇALVES PRUDENTE',
    razao_social: 'UNIODONTO GOIANIA COOPERATIVA DE CIRURGIÕES DENTISTAS',
    uf: 'GO',
    cargo_representante: 'REPRESENTANTE ',
    nome_fantasia: 'UNIODONTO GOIANIA',
    cep: '74215030',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '62',
    data_registro: '1998-12-17',
    logradouro: 'RUA T-27',
  },
  {
    numero: '670',
    telefone: '39528859',
    registro_ans: '343056',
    complemento: '',
    fax: '39528859',
    id: 1032,
    bairro: 'JD. LEONÍDIA',
    email: 'uniodonto@uniodontojac.com.br',
    cnpj: '00531736000196',
    cidade: 'Jacareí',
    representante_legal: 'GLÓRIA DE FÁTIMA CHAVES',
    razao_social: 'UNIODONTO JACAREÍ COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE JACAREÍ',
    cep: '12327070',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '12',
    data_registro: '1998-12-18',
    logradouro: 'AVENIDA MAJOR ACÁCIO FERREIRA',
  },
  {
    numero: '46',
    telefone: '34415754',
    registro_ans: '401919',
    complemento: 'LOJA 01',
    fax: '34415754',
    id: 1033,
    bairro: 'CENTRO',
    email: 'uniodonto@leopoldina.com.br',
    cnpj: '02021621000187',
    cidade: 'Leopoldina',
    representante_legal: 'MARCELO RESENDE VIEIRA',
    razao_social: 'UNIODONTO LEOPOLDINA - COOPERATIVA ODONTOLÓGICA',
    uf: 'MG',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: '',
    cep: '36700000',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '32',
    data_registro: '1999-03-11',
    logradouro: 'RUA JOSÉ PERES',
  },
  {
    numero: '411',
    telefone: '27629645',
    registro_ans: '300195',
    complemento: '',
    fax: '2227593737',
    id: 1034,
    bairro: 'CENTRO',
    email: 'gerencia@uniodontomacae.com.br',
    cnpj: '72515208000154',
    cidade: 'Macaé',
    representante_legal: 'MARCOS STHEL ANTUNES',
    razao_social: 'UNIODONTO MACAÉ - COOPERATIVA ODONTOLÓGICA',
    uf: 'RJ',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO MACAE',
    cep: '27910310',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '22',
    data_registro: '1998-12-18',
    logradouro: 'RUA MARECHAL DEODORO',
  },
  {
    numero: '278',
    telefone: '221233300',
    registro_ans: '321125',
    complemento: '',
    fax: '221233300',
    id: 1035,
    bairro: 'FAROL',
    email: 'uniodonto@uniodontomaceio.com.br',
    cnpj: '24243925000121',
    cidade: 'Maceió',
    representante_legal: 'JOSE ZENOU COSTA FILHO',
    razao_social: 'UNIODONTO MACEIÓ COOPERATIVA ODONTOLÓGICA',
    uf: 'AL',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO MACEIO',
    cep: '57051600',
    regiao_operacao: 3,
    modalidade: 'Cooperativa odontológica',
    ddd: '08',
    data_registro: '1998-12-22',
    logradouro: 'AV. SANTA RITA DE CASSIA',
  },
  {
    numero: '513',
    telefone: '32271150',
    registro_ans: '381144',
    complemento: '',
    fax: '',
    id: 1036,
    bairro: 'ZONA 02',
    email: 'uniodonto@uniodontomaringa.com.br',
    cnpj: '01367538000100',
    cidade: 'Maringá',
    representante_legal: 'VAMPRÉ LUIZ CARDOSO OLIVEIRA',
    razao_social: 'UNIODONTO MARINGA COOPERATIVA ODONTOLOGICA',
    uf: 'PR',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE MARINGA',
    cep: '87010060',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '44',
    data_registro: '1998-12-16',
    logradouro: 'AVENIDA PAPA JOAO XXIII',
  },
  {
    numero: '263',
    telefone: '26718785',
    registro_ans: '382337',
    complemento: 'GRUPO 102',
    fax: '',
    id: 1037,
    bairro: 'CENTRO',
    email: 'presidencia@uniodonto-metropolitana.com.br',
    cnpj: '01066312000160',
    cidade: 'Duque de Caxias',
    representante_legal: 'FLÁVIO ARAÚJO DE ASSIS',
    razao_social: 'UNIODONTO METROPOLITANA COOPERATIVA ODONTOLÓGICA.',
    uf: 'RJ',
    cargo_representante: 'DIRETOR-PRESIDENTE',
    nome_fantasia: 'UNIODONTO DUQUE DE CAXIAS',
    cep: '25070330',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '21',
    data_registro: '1998-12-29',
    logradouro: 'AVENIDA PRESIDENTE VARGAS',
  },
  {
    numero: '266',
    telefone: '33161115',
    registro_ans: '303291',
    complemento: '',
    fax: '33162990',
    id: 1038,
    bairro: 'NOVA BETANIA',
    email: 'gerencia@uniodontomossoro.com.br',
    cnpj: '02313780000155',
    cidade: 'Mossoró',
    representante_legal: 'FRANCISCO AVES DE OLIVEIRA',
    razao_social:
      'UNIODONTO MOSSORÓ - COOPERATIVA DOS CIRURGIÕES DENTISTAS DE MOSSORÓ E REGIÃO OESTE',
    uf: 'RN',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO MOSSORÓ',
    cep: '59603200',
    regiao_operacao: 6,
    modalidade: 'Cooperativa odontológica',
    ddd: '84',
    data_registro: '1998-12-24',
    logradouro: 'AV DIOCESANA',
  },
  {
    numero: '472',
    telefone: '35213567',
    registro_ans: '419729',
    complemento: '',
    fax: '',
    id: 1039,
    bairro: 'SÃO FRANCISCO',
    email: 'UNIODONTOPASSOS@PASSOSNET.COM.BR',
    cnpj: '02768410000102',
    cidade: 'Passos',
    representante_legal: 'LUIZ FERNANDO LEMOS REIS',
    razao_social: 'UNIODONTO PASSOS - COOPERATIVA ODONTOLÓGICA',
    uf: 'MG',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO PASSOS',
    cep: '37902000',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '35',
    data_registro: '2015-03-24',
    logradouro: 'RUA BONSUCESSO',
  },
  {
    numero: '110',
    telefone: '31253040',
    registro_ans: '361593',
    complemento: '10º andar - Edifício Santa Lúcia ',
    fax: '31593181',
    id: 1040,
    bairro: 'Bela Vista ',
    email: 'ans@uniodontopaulista.com.br',
    cnpj: '96396395000162',
    cidade: 'São Paulo',
    representante_legal: 'LUIZ EDUARDO ZACCHARIAS',
    razao_social:
      'UNIODONTO PAULISTA-FEDERAÇÃO DAS COOPERATIVAS ODONTOLÓGICAS DO ESTADO DE SÃO PAULO',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO PAULISTA',
    cep: '01331010',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '11',
    data_registro: '1998-12-18',
    logradouro: 'Rua Silvia ',
  },
  {
    numero: '421',
    telefone: '32810003',
    registro_ans: '402109',
    complemento: 'SALA 206, 2 ANDAR',
    fax: '32810003',
    id: 1041,
    bairro: 'CENTRO',
    email: 'uniodonto@uniodontopauloafonso.com.br',
    cnpj: '02772726000178',
    cidade: 'Paulo Afonso',
    representante_legal: 'CYNARA MAIA DE OLIVEIRA',
    razao_social:
      'UNIODONTO PAULO AFONSO COOPERATIVA DE TRABALHO ODONTOLÓGICO LTDA.',
    uf: 'BA',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO PAULO AFONSO',
    cep: '48601260',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '75',
    data_registro: '1999-03-15',
    logradouro: 'AV. GETULIO VARGAS',
  },
  {
    numero: '1352',
    telefone: '34011770',
    registro_ans: '346004',
    complemento: '',
    fax: '34011770234',
    id: 1042,
    bairro: 'CENTRO',
    email: 'atendimento@uniodontopiracicaba.com.br',
    cnpj: '52204526000197',
    cidade: 'Piracicaba',
    representante_legal: 'CLAUDIO ROBERTO ZAMBELLO',
    razao_social: 'UNIODONTO PIRACICABA - COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE PIRACICABA',
    cep: '13400123',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '19',
    data_registro: '1998-12-16',
    logradouro: 'RUA ALFARES JOSÉ CAETANO ',
  },
  {
    numero: '1470',
    telefone: '35611165',
    registro_ans: '378941',
    complemento: '',
    fax: '35611165',
    id: 1043,
    bairro: 'CENTRO',
    email: 'uniopirass@uniodontopirassununga.com.br',
    cnpj: '02260283000136',
    cidade: 'Pirassununga',
    representante_legal: 'EDGAR SAGGIORATTO',
    razao_social: 'UNIODONTO PIRASSUNUNGA - COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO DE PIRASSUNUNGA',
    cep: '13630082',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '19',
    data_registro: '1998-12-16',
    logradouro: 'RUA JOAQUIM PROCÓPIO DE ARAÚJO',
  },
  {
    numero: '618',
    telefone: '',
    registro_ans: '315818',
    complemento: '',
    fax: '',
    id: 1044,
    bairro: 'CENTRO',
    email: 'uniodontopg@uol.com.br',
    cnpj: '82621210000161',
    cidade: 'Ponta Grossa',
    representante_legal: 'RUBENS PUPO BANDEIRA',
    razao_social: 'UNIODONTO PONTA GROSSA COOPERATIVA ODONTOLÓGICA',
    uf: 'PR',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO PONTA GROSSA',
    cep: '84010210',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '',
    data_registro: '1998-12-16',
    logradouro: 'RUA BARÃO DO CERRO AZUL',
  },
  {
    numero: '914',
    telefone: '33024000',
    registro_ans: '366439',
    complemento: '',
    fax: '33024077',
    id: 1045,
    bairro: 'INDEPENDÊNCIA',
    email: 'regulacao@uniodontopoa.com.br',
    cnpj: '88938089000182',
    cidade: 'Porto Alegre',
    representante_legal: 'JULIO CESAR CORDOVA MACIEL',
    razao_social: 'UNIODONTO PORTO ALEGRE COOPERATIVA ODONTOLOGICA LTDA',
    uf: 'RS',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO PORTO ALEGRE COOPERATIVA ODONTOLOGICA LTDA',
    cep: '90035072',
    regiao_operacao: 4,
    modalidade: 'Cooperativa odontológica',
    ddd: '51',
    data_registro: '1998-12-17',
    logradouro: 'AV. INDEPENDÊNCIA',
  },
  {
    numero: '697',
    telefone: '32288118',
    registro_ans: '344451',
    complemento: '',
    fax: '',
    id: 1046,
    bairro: 'SANTA MARIA',
    email: 'gerencia@uniodontouberlandia.com.br',
    cnpj: '26185199000163',
    cidade: 'Uberlândia',
    representante_legal: 'RICARDO MANOEL LOURENÇO',
    razao_social: 'UNIODONTO REGIONAL COOPERATIVA ODONTOLOGICA',
    uf: 'MG',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO MINAS',
    cep: '38408056',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '34',
    data_registro: '1998-12-17',
    logradouro: 'AV JOÃO XXIII',
  },
  {
    numero: '64',
    telefone: '',
    registro_ans: '406121',
    complemento: '',
    fax: '33551752',
    id: 1047,
    bairro: 'COMERCIAL',
    email: 'uniodonto@uniodontoresende.com.br',
    cnpj: '03150035000103',
    cidade: 'Resende',
    representante_legal: 'ANA PAULA DA COSTA',
    razao_social: 'UNIODONTO RESENDE - COOPERATIVA ODONTOLOGICA',
    uf: 'RJ',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO RESENDE COOPERATIVA ODONTOLOGICA',
    cep: '27541140',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '',
    data_registro: '1999-07-07',
    logradouro: 'RUA ISAAC DAVID HALPERN',
  },
  {
    numero: '263',
    telefone: '32321563',
    registro_ans: '367966',
    complemento: '',
    fax: '',
    id: 1048,
    bairro: 'CENTRO',
    email: 'uniodonto@uniodontoriogrande.com.br',
    cnpj: '02662309000172',
    cidade: 'Rio Grande',
    representante_legal: 'DANIELI DUVAL PINTO DEVILLA',
    razao_social: 'UNIODONTO RIO GRANDE-LITORAL COOPERATIVA ODONTOLOGICA LTDA',
    uf: 'RS',
    cargo_representante: 'SUPERINTENDENTE',
    nome_fantasia: '',
    cep: '96200350',
    regiao_operacao: 6,
    modalidade: 'Cooperativa odontológica',
    ddd: '53',
    data_registro: '1998-12-29',
    logradouro: 'RUA LUIZ LOREA',
  },
  {
    numero: '64',
    telefone: '32257671',
    registro_ans: '305421',
    complemento: '1º ANDAR - EDIF. SAMPAIO',
    fax: '32868554',
    id: 1049,
    bairro: 'SÃO GERALDO',
    email: 'uniodontors@uniodonto-rs.com.br',
    cnpj: '72120124000111',
    cidade: 'Porto Alegre',
    representante_legal: 'IRNO AUGUSTO PRETTO',
    razao_social: 'UNIODONTO RS FEDERACAO DAS UNIODONTOS DO RGS LTDA',
    uf: 'RS',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO/RS',
    cep: '90220050',
    regiao_operacao: 3,
    modalidade: 'Cooperativa odontológica',
    ddd: '51',
    data_registro: '1998-12-23',
    logradouro: 'RUA QUINTINO BANDEIRA',
  },
  {
    numero: '373',
    telefone: '32150706',
    registro_ans: '327441',
    complemento: '',
    fax: '32151561',
    id: 1050,
    bairro: 'CENTRO',
    email: 'uniodonto@uniodontojf.com.br',
    cnpj: '01290793000193',
    cidade: 'Juiz de Fora',
    representante_legal: 'MAGALI DE FREITAS MACIEL',
    razao_social:
      'UNIODONTO SUDESTE MINEIRO COOPERATIVA DE SAÚDE ODONTOLÓGICA LTDA',
    uf: 'MG',
    cargo_representante: 'DIRETORA PRESIDENTE',
    nome_fantasia: 'UNIODONTO SUDESTE MINEIRO ',
    cep: '36016290',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '32',
    data_registro: '1998-12-21',
    logradouro: 'RUA OSCAR VIDAL',
  },
  {
    numero: '05',
    telefone: '36216063',
    registro_ans: '314871',
    complemento: '',
    fax: '',
    id: 1051,
    bairro: 'CENTRO',
    email: 'gerencia@uniodontosudoeste.com.br',
    cnpj: '02033677000151',
    cidade: 'Rio Verde',
    representante_legal: 'FERNANDO FERREIRA DE ALMEIDA',
    razao_social:
      'UNIODONTO SUDOESTE GOIANO - COOPERATIVA DE TRABALHO ODONTOLOGICO',
    uf: 'GO',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: '',
    cep: '75901120',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '64',
    data_registro: '1998-12-17',
    logradouro: 'RUA NIVALDO RIBEIRO',
  },
  {
    numero: '12',
    telefone: '21073350',
    registro_ans: '363171',
    complemento: '',
    fax: '33486184',
    id: 1052,
    bairro: 'VILA SANTA CECILIA',
    email: 'uniodontosulfluminense@uniodontosf.com.br',
    cnpj: '72261803000100',
    cidade: 'Volta Redonda',
    representante_legal: 'KÊNIA APARECIDA DA SILVA ACCIARITO',
    razao_social: 'UNIODONTO SUL FLUMINENSE COOP DE TRAB ODONTOLOGICO LTDA',
    uf: 'RJ',
    cargo_representante: 'REPRESENTANTE',
    nome_fantasia: 'UNIDONTO SUL FLUMINENSE',
    cep: '27260500',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '24',
    data_registro: '1998-12-16',
    logradouro: 'RUA PROFESSORA CLÉLIA',
  },
  {
    numero: '2597',
    telefone: '33626062',
    registro_ans: '335525',
    complemento: '',
    fax: '',
    id: 1053,
    bairro: 'CENTRO',
    email: 'uniodontosaocarlos@terra.com.br',
    cnpj: '54912241000136',
    cidade: 'São Carlos',
    representante_legal: 'NIVEA CELIA BONADIO COELHO',
    razao_social: 'UNIODONTO SÃO CARLOS -  COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'DIRETORA PRESIDENTE',
    nome_fantasia: 'UNIODONTO SÃO CARLOS',
    cep: '13560241',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '16',
    data_registro: '1998-12-16',
    logradouro: 'RUA 15 DE NOVEMBRO',
  },
  {
    numero: '2651',
    telefone: '32118400',
    registro_ans: '303259',
    complemento: '',
    fax: '32346005',
    id: 1054,
    bairro: 'CENTRO',
    email: 'uniodorp@uniodontoriopreto.com.br',
    cnpj: '53206108000100',
    cidade: 'São José do Rio Preto',
    representante_legal: 'JOSÉ CARLOS AFONSO CUGINOTTI',
    razao_social: 'UNIODONTO SÃO JOSÉ DO RIO PRETO - COOPERATIVA ODONTOLÓGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO',
    cep: '15010110',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '17',
    data_registro: '1998-12-16',
    logradouro: 'RUA INDEPENDENCIA ',
  },
  {
    numero: '728',
    telefone: '34110522',
    registro_ans: '319350',
    complemento: '',
    fax: '36292511',
    id: 1055,
    bairro: 'CENTRO',
    email: 'uniodonto@uniodontotaubate.com.br',
    cnpj: '02030488000125',
    cidade: 'Taubaté',
    representante_legal: 'ALEXANDRE CURSINO DE MOURA SANTOS',
    razao_social: 'UNIODONTO TAUBATÉ COOPERATIVA DE TRABALHO ODONTOLOGICO',
    uf: 'SP',
    cargo_representante: 'DIRETOR PRESIDENTE',
    nome_fantasia: 'UNIODONTO TAUBATE',
    cep: '12020030',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '12',
    data_registro: '1998-12-17',
    logradouro: 'RUA DR. SOUZA ALVES ',
  },
  {
    numero: '618',
    telefone: '33347700',
    registro_ans: '370568',
    complemento: '',
    fax: '',
    id: 1056,
    bairro: 'CENTRO',
    email: 'gerencia@uniodontouberaba.com.br',
    cnpj: '17333055000116',
    cidade: 'Uberaba',
    representante_legal: 'WASHINGTON TADEU NASCIMENTO',
    razao_social:
      'UNIODONTO UBERABA - COOPERATIVA DE ASSISTÊNCIA À SAÚDE ODONTOLÓGICA LTDA',
    uf: 'MG',
    cargo_representante: 'DIRETOR EXECUTIVO',
    nome_fantasia: 'UNIODONTO ',
    cep: '38060340',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '34',
    data_registro: '1998-12-17',
    logradouro: 'RUA CORONEL MANOEL BORGES',
  },
  {
    numero: '365',
    telefone: '31532900',
    registro_ans: '382655',
    complemento: '',
    fax: '31532746',
    id: 1057,
    bairro: 'CRUZ',
    email: 'admwanda@uniodontovalehistorico.com.br',
    cnpj: '02149799000108',
    cidade: 'Lorena',
    representante_legal: 'WANDA MARIA RICOTA DE MELLO',
    razao_social: 'UNIODONTO VALE HISTORICO COOPERATIVA ODONTOLOGICA',
    uf: 'SP',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO VALE HISTORICO COOPERATIVA ODONTOLOGICA',
    cep: '12606080',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '12',
    data_registro: '1998-12-16',
    logradouro: 'PRAÇA DOUTOR GAMA RODRIGUES',
  },
  {
    numero: '665',
    telefone: '40094664',
    registro_ans: '345318',
    complemento: '',
    fax: '40094665',
    id: 1058,
    bairro: 'TIROL',
    email: 'gerencia@uniodontorn.com.br',
    cnpj: '08237810000178',
    cidade: 'Natal',
    representante_legal: 'EUGÊNIO CARLOS ARAÚJO',
    razao_social:
      'UNIODONTO/RN - COOPERATIVA ODONTOLOGICA DO RIO GRANDE DO NORTE',
    uf: 'RN',
    cargo_representante: 'PRESIDENTE',
    nome_fantasia: 'UNIODONTO/RN',
    cep: '59020110',
    regiao_operacao: 5,
    modalidade: 'Cooperativa odontológica',
    ddd: '84',
    data_registro: '1998-12-17',
    logradouro: 'RUA AÇU',
  },
];
